### ISSUE TITLE
Impossible to get correct interval from datetime

### ISSUE THREAD

**Issue by michaelmior** [wit-ai/node-wit#178]
When I wit returns a datetime entity for a phrase such as

> 07/11/2018 at 11:00 AM for 60 minutes

I get back an interval datetime **from 7/11/2018, 11:00:00 AM to 7/11/2018, 12:00:00 PM**.

However, for a phrase such as

> 07/11/2018 at 11:00 AM - 12:00 PM

These two clearly have the same intended meaning, but for the second, I get back an interval datetime **from 7/11/2018, 11:00:00 AM to 7/11/2018, 1:00:00 PM**. This means it's currently not possible for my application to handle both of these scenarios. Any help would be appreciated.

**Comment by stopachka** [comment]
Hey @michaelmior, this would be best posted in https://github.com/facebook/duckling/ -- the library that backs our datetime parsing. Maintainers there can decide on what the full fix is there

**Comment by patapizza** [comment]
`07/11/2018 at 11:00 AM for 60 minutes` returns 11am-12pm.
`07/11/2018 at 11:00 AM - 12:00 PM` returns 11am-12:01pm.

Fix upcoming to return 11am-12:01pm for both.

**Comment by patapizza** [comment]
This is now fixed.

**Comment by michaelmior** [comment]
Could you clarify how each of these is expected to parse now?

**Comment by patapizza** [comment]
See my comment above: both return the interval `[11am - 12:01pm[`. You can try it out in the Wit UI or on the API to see the output.
Hope this helps.

**Comment by michaelmior** [comment]
Sorry, I must have spaced out when I was reading this thread earlier. Thanks!

**Comment by michaelmior** [comment]
I am still seeing the second example give me the time interval from 11am-1pm

**Comment by blandinw** [comment]
@michaelmior I cannot reproduce your issue. This is what I'm getting:

![image](https://user-images.githubusercontent.com/413070/44556914-dfafc380-a6f0-11e8-9adb-94309f06e570.png)

![image](https://user-images.githubusercontent.com/413070/44556918-e0e0f080-a6f0-11e8-81dc-a29385e0422d.png)

Can you confirm this is fixed for you?

**Comment by michaelmior** [comment]
Hmm, the specific examples I mentioned in the issue are fixed, but others are still broken

> today from 9pm for 60 minutes

gives what I would expect, 9-10:01pm

> today from 9-10pm

gives 9-11pm

**Comment by blandinw** [comment]
> "today from 9-10pm" ->  [9pm-11pm[ 

This is expected. The upper bound is exclusive and the grain (granularity) here is "hour", which means that the inclusive notation would be [9pm-10pm]. In other words, you need to subtract the grain unit from the upper bound.

"9-10:01pm" has a granularity minute, but the same logic applies.

**Comment by michaelmior** [comment]
Okay, I'll check the granularity as this may solve my problem. Thanks!

**Comment by michaelmior** [comment]
Looking at the granularity does indeed solve the problem :)

**Comment by blandinw** [comment]
Glad to hear, thank you for your feedback @michaelmior!
